README.md:
  filename: "README.md"
  supported-systems: [list]

colorscheme.txt:
  filename: doc/colorscheme.txt
  supported-systems: [list]

base16.lua:
  filename: lua/colors/{{ scheme-system }}-{{ scheme-slug }}.lua
  supported-systems: [base16]

base16.vim:
  filename: colors/{{ scheme-system }}-{{ scheme-slug }}.vim
  supported-systems: [base16]

base24.lua:
  filename: lua/colors/{{ scheme-system }}-{{ scheme-slug }}.lua
  supported-systems: [base24]

base24.vim:
  filename: colors/{{ scheme-system }}-{{ scheme-slug }}.vim
  supported-systems: [base24]
